/******************************************************************************
 *  File Name:
 *    net_data_package.hpp
 *
 *  Description:
 *    Interface for collecting, transmitting, and processing the pieces of data
 *    generated by the drone control system.
 *
 *  2022 | Brandon Braun | brandonbraun653@gmail.com
 *****************************************************************************/

#pragma once
#ifndef DC_NET_DATA_PACKAGE_HPP
#define DC_NET_DATA_PACKAGE_HPP


namespace DC::NET
{
  /*---------------------------------------------------------------------------
  Public Functions
  ---------------------------------------------------------------------------*/
  /**
   * @brief Powers up the data packaging infrastructure
   */
  void initDataPackage();


  /**
   * @brief Processes stick inputs for new data, shipping it to the drone
   */
  void procStickInputs();


  /**
   * @brief Processes system state information, shipping it to the drone
   */
  void procStateData();

}  // namespace DC::NET

#endif  /* !DC_NET_DATA_PACKAGE_HPP */
